; PROGRAM TO PRINT AND DISPLAY 'HELLO WORLD' STRING WITH PROGRAMMER NAME...

section .data
	msg01 db 'Hello World', 13,10	      		  ; STORING FIRST STRING (in msg01)...
	msg01_length equ $-msg01	          		  ; STORING LENGTH OF FIRST STRING (in msg01_length)...
	msg02 db 'My First ALP using NASM...', 13,10  ; STORING SECOND STRING (in msg02)...
	msg02_length equ $-msg02	                  ; STORING LENGTH OF SECOND STRING (in msg02_length)...

section .text
	global _start

_start :
	MOV EDX, msg01_length ; DISPLAYS FIRST MESSAGE(msg01)...
	MOV ECX, msg01
	MOV EBX, 1
	MOV EAX, 4			
	INT 80H

	MOV EDX, msg01_length ; DISPLAYS SECOND MESSAGE(msg02)...
	MOV ECX, msg02
	MOV EBX, 1
	MOV EAX, 4			
	INT 80H 

	MOV EAX, 1			  ; EXIT...
	INT 80H
